apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stateinspector-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stateinspector-reader
subjects:
  - kind: ServiceAccount
    name: stateinspector
    namespace: stateinspector
